language: python
python:
  - "3.7-dev"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python3 services/movies.py
  - python3 services/showtimes.py
  - python3 services/bookings.py
  - python3 services/user.py